apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZDekNDQXZPZ0F3SUJBZ0lDQitZd0RRWUpLb1pJaHZjTkFRRUxCUUF3RnpFVk1CTUdBMVVFQ2hNTWJHaHAKYm1RdVpHeG9MbVJsTUI0WERUSXpNREV6TURBeE1UZ3lPVm9YRFRJME1ERXpNREF4TVRneU9Wb3dGekVWTUJNRwpBMVVFQ2hNTWJHaHBibVF1Wkd4b0xtUmxNSUlDSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDCkFnRUF3clJQS056eDJNTUNobHJVQW1GSGF2cjk2anBqRGpoT1d3RHMydVpWRVlQR21yN1VINTlnZjg4STRaWnoKTjJpck5vTlprUlFZalp1MGhOS0dJOEtCOW9IVGcyMzRzY0dlYTJSN09jaVh0OEpUN2ZRZy91dmZYWEZiUGpMUwpMeEpaeUdTMWhqL0RkQjJtU1FYZmRpbGdBeUlkMlFiL1dPeGJWT21PdWpITFdMSDVXQTdXMjZYNnpPRm5CMmkyClcrNDAvcWJOVEZKOFE5aFFpYnAxTXZKckdwYjI2VzFpQmx0czBmV0tpODArNTc0aUc3M2F2N2lWc21rZVNRbmIKNHVCS3ZXY1l4MHpMZ0o5OGgwQXVmczErcnljQk8yVEpmU1RSd2RiK1dNSG9RMVF6aTk4aWJTK29sVDhEWGNNaQp4SGpFQVZKL0pVL0YyRi9wUS9rL0kxUXFpcEIrWEovaEJFTWc3R25pY2p5SURiVTNZVmtnc2xBTGFLQVlXTnY2CjBkMEVFclJ0M0JNL0Y0RHh0c1NsNkJzU0ZaVWdnRFVKczJJYjhwOE1iWGs0ckZsekV3OCtNVitvZHNhSnRCVGYKcTRrb2RjQWpwZVpVQjZyUDlJcXozaHYzbVZQWjUrT1RrbHl2SW43ZG9hWmRZcW1JL0NGNnU3R0FOTXFEcE9RcQozaXJDZml3ZjNveUJEZlBSS1ptWkJaWTdyR0s5TTc2allialYrM0dRdWM2bVFJdlZjendURVcwc3hDNTZkV1AxCkxXZS9NNnBJWHFONzZYVXNDUDFuN2t3ODI1Q1JjSEdSQkkwVHAwM2xxU0dLT3l1ZWprbUV6dTR5Y1BuS3JZZ1IKTGlyN0YvakVDOFVBQkE1VTVrT3FtczkybWY1RlE2c2NLWW0rN2pDZHNnSHRMSkVDQXdFQUFhTmhNRjh3RGdZRApWUjBQQVFIL0JBUURBZ0tFTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQ0JnZ3JCZ0VGQlFjREFUQVBCZ05WCkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlI5RUJjcGlEY3JheHZWbHRHOWtZNWVIbTN0V3pBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FnRUF1NmkzbWYrcEVRUmtWTGIzMTRKTFc1bSt5L1FrSU1xeSsvMlVaR2tnVDNMZwpTbnR1emVSdzcvSVhGTi9GTWVuTVlQRVZUZnZ0enFZQTNLSGhZaVorVityaDVXdy8yYVpISG53UGhybFpDTlZXCnRXR1Q3SmJUS0dhdHpiaC9wOHRab3VPNWVwU3NzNDQ5UU1Qc0V1dkdmWFlWK1FGbGQrTjZUWnBra0MxRTRYV2YKVFZUUDV4bjJTVHZuZTdIVldtVkUvcnIxSW5WVnJWS2hXaFVwMVN2TTl5dzZWZ0VnNEhSOUlPQzRhYU5ZY1crRApwMXJwKzBzWVVra2I3azFyZXc3UkNmblJ0ZXVSb2xvRkJUeEIyaDFxM1BLVkVzVEc0aDY5S1o0SVBlNGQ0Sm1OCjlveWUwSnJrV3Q5RHZmbHkycnJKd2djcCt3U253SVltdzNDaTRlUWNlNXdQMVQyRmtDVE84VStPcWdMaTRpUUMKY1BYT0xleW1TL1ZwaXVrYm1WcWx1RE5PZmdUeXdkS081eEs4ditpcFpqL2hwNzJmNEhDbE13RnhhYTE0SFVxSQpUZ2VqT0hTcnBLYkdveW00U2xrNTEzZy8wb1dpNzJBU1lGZlY0SUVCQy9xQnNlOFRDNDRidG5GN3p1bzUvaml4CnBsTU1jTlNqVnFYazFIcDJxYTRJU2llWmJ1TGNiQnZJNWppN081WngzT3BrTXRPTGxFSG04Um5jbGRiTDNjK1EKUG15ZmdRZXhNZXdFSG84WGFSNnpVS1RqUzRGZCtKZGZzSVdsaTlyNlVqTEx4Q2xPeUo4blU3QkFIYkFob01GRgpDdzNPUGtCYjV0dGplbjd1Tko3WUhENU1EQXp1Mi9vV2pHbzBudzNlcTh6dS9HYkFCY0M4L2xVeC9IUFlveW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: sidecar-injector
      namespace: sidecar-injector
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: sidecar-injector.lhind.dlh.de
  namespaceSelector:
    matchLabels:
      sidecar-injection: enabled
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10