namespace: sidecar-injector

resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- configmap.yaml
- nginx-configmap.yaml
- nginx-configmap-2.yaml

images:
- name: sidecar-injector
  newName: quay.io/erlis_balla/sidecar-injector
  newTag: 0.13.8
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
